# ansible/roles/app_deploy/tasks/main.yml
- name: Copy application files
  copy:
    src: "{{ item }}"
    dest: "/var/www/app/"
  with_items:
    - "frontend/"
    - "backend/"

- name: Install npm dependencies
  npm:
    path: "/var/www/app/backend"
    state: present

- name: Set environment variables
  template:
    src: env.j2
    dest: /var/www/app/backend/.env
