# ansible/roles/nodejs/tasks/main.yml
---
- name: Add NodeSource repository
  shell: |
    curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -
  args:
    executable: /bin/bash

- name: Install Node.js
  apt:
    name: nodejs
    state: present
    update_cache: yes

- name: Install npm
  apt:
    name: npm
    state: present

- name: Install PM2 globally
  npm:
    name: pm2
    global: yes
    state: present
