- name: Deploy Web Application
  hosts: web
  become: true
  roles:
    - nginx
    - reacjs

- name: Setup DB
  hosts: database
  become: true
  roles:
    - database_setup

- name: Deploy Backend
  hosts: backend
  vars:
    db_host: "your-db-host"
    db_user: "your-db-user"
    db_password: "{{ vault_db_password }}" # Use Ansible vault for sensitive data
    db_name: "your-db-name"
    db_port: "your-db-port"
  become: true
  roles:
    - nodejs
