- name: Deploy Web Application
  hosts: web
  become: true
  roles:
    - nginx_setup
    - reactjs

- name: Setup DB
  hosts: database
  become: true
  roles:
    - db_setup

- name: Deploy Backend
  hosts: backend
  vars:
    db_host: "{{ db_host }}"
    db_user: "{{ db_user }}"
    db_password: "{{ db_password }}"
    db_name: "{{ db_name }}"
    db_port: "{{ db_port }}"
  become: true
  roles:
    - nodejs
