name: Terraform Apply

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  terraform:
    if: github.event.pull_request.merged == true
    name: Terraform Apply
    runs-on: ubuntu-latest
    env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          TF_VAR_DB_PASSWORD: ${{secrets.TF_VAR_DB_PASSWORD}}
          ANSIBLE_VAULT_PASSWORD: ${{secrets.ANSIBLE_VAULT_PASSWORD}}
          SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.0

      - name: Terraform Format Check
        working-directory: ./terraform
        run: terraform fmt -check -recursive

      - name: Terraform Init
        working-directory: ./terraform
        run: terraform init

      - name: Terraform Validate
        working-directory: ./terraform
        run: terraform validate

      - name: Terraform Plan
        working-directory: ./terraform
        run: terraform plan -var="db_password=$TF_VAR_DB_PASSWORD"
        
      - name: Terraform Apply
        working-directory: ./terraform
        run: terraform apply -auto-approve -var="db_password=$TF_VAR_DB_PASSWORD"